objects/sfal__Alert__c.object
<CustomObject>
    <fields>
        <fullName>sfal__Advisee__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Lookup to the advisee Contact that the Alert is related to.</description>
        <label>Advisee Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Alerts</relationshipLabel>
        <relationshipName>Alerts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>sfal__Comments__c</fullName>
        <description>Comments about the Alert.</description>
        <label>Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>sfal__Status__c</fullName>
        <description>Status of the Alert.</description>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Acknowledged: In Progress</fullName>
                </value>
                <value>
                    <fullName>Acknowledged: Redirected</fullName>
                </value>
                <value>
                    <fullName>Closed: Action Taken</fullName>
                </value>
                <value>
                    <fullName>Closed: No Action Needed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Alert</label>
    <nameField>
        <displayFormat>AL-{0000}</displayFormat>
        <label>Alert #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Alerts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/EmailAfterDeleteTest.cls
@isTest
public class EmailAfterDeleteTest
{
    @isTest(SeeAllData=true)
    static void testEmailAfterDelete()
    {
        
        sfal__Alert__C testAlert = new sfal__Alert__c ();
        testAlert.RecordTypeId = '0121U000000MknCQAS';
        testAlert.sfal__Advisee__c = '0031U00000QpjLuQAJ';
        testAlert.sfal__Status__c = 'New';
        testAlert.sfal__Comments__c = 'Test Alert';
        insert testAlert;
        
        
        Test.startTest();
        
        delete testAlert;
        
        Test.stopTest();
 
    }
}